### PR TITLE
Start time improvements

### LINKED ISSUE #31: Some tags are always pulled
## Describe the bug

For a reason that is not clear to me, tags that do not match the regular expression `^[a-zA-Z0-9.-]$` are always pulled.
I don't see a reason for that. No comment was left. We should remove this unless we find a valid reason.

### PR DESCRIPTION
**Pull request by jaredoconnell**
## Changes introduced with this PR

This fixes #31 and #5 

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by mfleader — APPROVED** [review]

File: connector.go [hunk 1]
```diff
@@ -139,7 +136,8 @@ func (c connector) pullImage(ctx context.Context, image string) error {
 		}
 		parts := strings.Split(image, ":")
 		tag := parts[len(parts)-1]
-		if len(parts) > 1 && tagRegexp.MatchString(tag) && tag != "latest" && imageExists {
+		// It appears that the tag check is to defer invalid tag errors to docker
+		if len(parts) > 1 && validTagRegexp.MatchString(tag) && tag != "latest" && imageExists {
 			return nil
 		}
```
Comment (webbnh) [inline connector.go]: So, if the pull policy is "If Not Present" and the image is present, it will still get pulled if the tag happens to be `latest`?  That seems likely to be surprising.  😒

(I realize that you're not creating or changing that behavior in this PR, but it seems like something that we should be aware of and consider changing, even if not in this PR.)

File: schema.go [hunk 2]
```diff
@@ -217,6 +217,22 @@ var Schema = schema.NewTypedScopeSchema[*Config](
 				schema.PointerTo(util.JSONEncode(string(ImagePullPolicyIfNotPresent))),
 				nil,
 			),
+			"startDelayMS": schema.NewPropertySchema(
+				schema.NewIntSchema(schema.PointerTo(int64(0)), schema.PointerTo(int64(10000)), nil),
```
Comment (webbnh) [inline schema.go]: Is the maximum required?  10s seems like an arbitrary value, and an arbitrarily low value, at that.  Since the maximum is not the default, would it hurt to pick something outlandishly high, just so that this doesn't unnecessarily constrain the user?  (Values like `4294967295`, `2147483648`, `2147483647` and `999999999` leap to mind, but there are other good ones....)

**Review by webbnh — APPROVED** [review]
Looks good.  I just have two items for you to consider.

File: connector.go (hunk 1 above)
Comment (jaredoconnell) [reply connector.go]: Do you think this deserves an issue, or do you think I should just remove that logic?

File: schema.go (hunk 2 above)
Comment (jaredoconnell) [reply schema.go]: It's not required. But this is meant to be used for workarounds. When I used this for a workaround, 500ms was enough. This 20 times that, so I think that's a large enough for any case.
This should only be used if absolutely necessary. Most users shouldn't need to use this.
Do you think that's okay?

File: connector.go (hunk 1 above)
Comment (webbnh) [reply connector.go]: I think that the behavior of the "If Not Present" policy should not depend on the image tag (at least, not if it's a legitimate tag for an image existing in a remote repository); therefore, I think the test for `tag != "latest"` should be removed from here.

Whether that should be done in this PR or not is up to you (I don't think that adding that change will overburden this PR).

If you agree that it should be removed but think it should be done in a separate PR, then an issue would be appropriate...but, instead of opening a new issue, you could (IMO) just post a PR for it....  🙃

File: schema.go (hunk 2 above)
Comment (webbnh) [reply schema.go]: If the maximum is not required, then I recommend omitting it and accepting any (positive) value (up to the limit of an `int64`...).

I understand that we hope that no one will _have_ to use this, but if we're going to go to the trouble of providing it, why should there be an upper limit on the delay?  What does it cost Arca, or what does it force the implementation to do, that limiting the delay to under 10s saves us from?  (Why is 20x the right number?)

Some user might find a novel use for this feature.  Why should we limit it?  (If there is a good reason, then I'm fine with that; however, if there is no reason, then lets not do it.)

Comment (jaredoconnell) [reply schema.go]: Updated.

File: connector.go (hunk 1 above)
Comment (jaredoconnell) [reply connector.go]: Updated.

File: connector.go [hunk 3]
```diff
@@ -39,10 +38,8 @@ func (c *connector) Deploy(ctx context.Context, image string) (deployer.Plugin,
 		return nil, err
 	}
 
-	//nolint:godox
-	// TODO: Make this sleep workaround no longer needed.
 	// It's required to not crash podman
-	time.Sleep(500 * time.Millisecond)
+	time.Sleep(time.Duration(c.config.Deployment.StartDelayMS) * time.Millisecond)
```
Comment (dbutenhof) [inline connector.go]: While waiting 0 milliseconds is fast, *not* waiting at all would be faster. It's not really a big deal, but I might be tempted to skip the call if the value is 0. 😁

**Review by dbutenhof — APPROVED** [review]

File: connector.go (hunk 3 above)
Comment (jaredoconnell) [reply connector.go]: Updated to include an if statement. That'll save a few CPU cycles.

File: connector.go [hunk 4]
```diff
@@ -39,10 +38,10 @@ func (c *connector) Deploy(ctx context.Context, image string) (deployer.Plugin,
 		return nil, err
 	}
 
-	//nolint:godox
-	// TODO: Make this sleep workaround no longer needed.
 	// It's required to not crash podman
-	time.Sleep(500 * time.Millisecond)
+	if c.config.Deployment.StartDelayMS > 0 {
+		time.Sleep(time.Duration(c.config.Deployment.StartDelayMS) * time.Millisecond)
+	}
```
Comment (dbutenhof) [inline connector.go:44]: You could have avoided the second fetch with a local, but that's an even smaller impact on time/CPU so I won't even comment on that. (Oops.)

**Review by dbutenhof — APPROVED** [review]

File: connector.go (hunk 4 above)
Comment (webbnh) [reply connector.go:44]: Hopefully Go has an common-expressions optimizer which will take care of that.  🙂

**Review by webbnh — APPROVED** [review]
👍
